packages:
  - app/frontend
  - app/backend

catalog:
  eslint: ^9.39.2
  prettier: ^3.5.3
  typescript: ^5.7.2

ignoredBuiltDependencies:
  - esbuild
  - unrs-resolver

onlyBuiltDependencies:
  - '@prisma/engines'
  - better-sqlite3
  - prisma
